[**LithiumX v1.0.7**](README.md)

***

[LithiumX](globals.md) / Exception

# Interface: Exception

Defined in: [src/Structures/Utils.ts:305](https://github.com/anantix-network/LithiumX/blob/720bc1bb802e250a8740a01a0f217198cffacb28/src/Structures/Utils.ts#L305)

## Properties

### cause

> **cause**: `string`

Defined in: [src/Structures/Utils.ts:308](https://github.com/anantix-network/LithiumX/blob/720bc1bb802e250a8740a01a0f217198cffacb28/src/Structures/Utils.ts#L308)

***

### message

> **message**: `string`

Defined in: [src/Structures/Utils.ts:306](https://github.com/anantix-network/LithiumX/blob/720bc1bb802e250a8740a01a0f217198cffacb28/src/Structures/Utils.ts#L306)

***

### severity

> **severity**: [`Severity`](type-aliases\Severity.md)

Defined in: [src/Structures/Utils.ts:307](https://github.com/anantix-network/LithiumX/blob/720bc1bb802e250a8740a01a0f217198cffacb28/src/Structures/Utils.ts#L307)
